var LANG = {
	'english': {
		'test_language': 'en',
		'update_now': 'Update Now',
		'skip_now': 'Not Now',
		'checking_version': 'checking new version',
		'copying_app': 'copying app',
		'already_downloading': 'Already downloading',
		'no_new_version': 'No new version exists',
		'new_version_detected': 'New version detected',
		'new_version_loading': 'New version loading ',
		'unpacking': 'unpacking: ',
		'show_hide': 'Show/Hide',
		'quit': 'Quit',
		'news_popup': "Popup news",
		'check_pudate': "Check update",
		'exit_program': "Exit program",
		'cut':'Cut',
		'copy':'Copy',
		'paste':'Paste'
	},
	'japanese': {
		'test_language': 'jp',
		'update_now': 'すぐに更新',
		'skip_now': '後で再度表示',
		'checking_version': 'バージョンを確認しています',
		'copying_app': '読込中',
		'already_downloading': 'ダウンロード完了',
		'no_new_version': '最新バージョンです',
		'new_version_detected': '更新を確認',
		'new_version_loading': '最新版をダウンロードしています ',
		'unpacking': 'インストールしています: ',
		'show_hide': '表示/非表示',
		'quit': '閉じる',
		'news_popup': "お知らせ",
		'check_pudate': "更新を確認",
		'exit_program': "終了",
		'cut':'カット',
		'copy':'コピー',
		'paste':'貼付'
	},
	'chinese': {
		'test_language': 'zh',
		'update_now': '立即更新',
		'skip_now': '暂不更新',
		'checking_version': '正在检查更新',
		'copying_app': '正在复制程序',
		'already_downloading': '更新包下载完毕',
		'no_new_version': '已是最新版本',
		'new_version_detected': '检查到新版本',
		'new_version_loading': '正在下载最新版本',
		'unpacking': '正在解压: ',
		'show_hide': '显示/隐藏',
		'quit': '退出',
		'news_popup': "新消息通知",
		'check_pudate': "检查更新",
		'exit_program': "退出程序",
		'cut':'剪切',
		'copy':'复制',
		'paste':'粘贴'
	}
}